services:
  - type: web
    name: baumapp
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: baumdb
          property: connectionString

databases:
  - name: baumdb
    databaseName: baumdb
    user: baumuser
